148 login page responsive
EddieTheCubeHead/Stagnum pull request #149
Opened 2024-03-26 15:54 UTC by ddevarsh7

Login page responsive is done.

2024-03-29 15:00 UTC, tuomasmustakallio requested changes
There are still scroll bars in the login page because the view takes up extra space and the image still streches and shrinks which should not happen. Rather just keep the image the same size and just leave excess of it out when resizing the screen.  Also this still uses the old green stagnum logo?

2024-04-01 19:04 UTC, OttoAhlfors requested changes
There are still scroll bars, and the picture still gets flattened

2024-04-15 14:03 UTC, tuomasmustakallio approved these changes

2024-04-15 14:04 UTC, OttoAhlfors approved these changes

2024-04-15 14:06 UTC, merged