format fix
EddieTheCubeHead/Stagnum pull request #210
Opened 2024-04-08 16:35 UTC by OttoAhlfors

2024-04-09 15:01 UTC, tuomasmustakallio commented
Could the PR title be changed if this also contains the token ticket?

2024-04-10 09:30 UTC, EddieTheCubeHead requested changes
Super minor grammatical corrections, but should be done anyways imo.

2024-04-10 09:30 UTC, EddieTheCubeHead commented on client/components/searchComponents/search.tsx
> +                    `Joining to pool failed with error : ${error.response.data.detail}`,
"Joinin **a** pool"

2024-04-10 09:30 UTC, EddieTheCubeHead commented on client/components/poolmanagerComponents/poolManager.tsx
> +                    `Sharing pool failed with error: ${error.response.data.detail}`,
"Sharing **a** pool"

2024-04-10 09:30 UTC, EddieTheCubeHead commented on client/components/buttons/iconButtons/showMoreIconButton.tsx
> +                    `Creating pool failed with error: ${error.response.data.detail}`,
"Creating **a** pool"

2024-04-10 19:44 UTC, EddieTheCubeHead submitted a review, later dismissed

2024-04-11 07:27 UTC, OttoAhlfors commented
Joining a pool failed with error : [object Object]
There is an issue with the details following different structures depending on the error leading to slightly not helpfull error messages

2024-04-11 09:13 UTC, tuomasmustakallio submitted a review, later dismissed

2024-04-11 13:05 UTC, tuomasmustakallio approved these changes

2024-04-11 13:13 UTC, merged