#336: Reworked terraform to use EC2 instead of ECS
EddieTheCubeHead/Stagnum pull request #337
Opened 2024-06-13 19:49 UTC by ekosfin

## Summary

Closes #336 This should reduce operational costs.

## Notable changes

Updated terraform to use EC2 instance instead of ECS

2024-06-22 12:23 UTC, ekosfin reviewed
@EddieTheCubeHead could you look though these comments.

2024-06-22 12:23 UTC, ekosfin commented on infra/main.tf
> +  name = "stagnum.com"
Is this domain correct?

2024-06-22 12:23 UTC, ekosfin commented on infra/main.tf
> +resource "aws_volume_attachment" "this" {
The postgres data should be stored here so that even if the ec2 instance would be destroyed

2024-06-22 12:23 UTC, ekosfin commented on infra/main.tf
> +  public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgP6TjSCjZS/VWhixYYevHGdzVN4jmlT5KH9va5CiBs elias.samuli@gmail.com"
You might want to update this to be your public ssh key if you need access to the server

2024-06-22 12:23 UTC, ekosfin commented on infra/main.tf
> +  ingress_rules       = ["http-80-tcp", "https-443-tcp", "all-icmp", "ssh-tcp"]
I am still a bit unsure of what ports need to be open, so I just test the usual

2024-06-22 12:23 UTC, ekosfin commented on infra/main.tf
> +    # TODO: Set values
I am still a bit unsure of these env variables. Please look over them

2024-06-22 12:23 UTC, ekosfin commented on infra/config/userdata.tftpl
> +wget https://raw.githubusercontent.com/EddieTheCubeHead/Stagnum/master/docker-compose-deploy.yml #TODO: edit this to be one from config once in main
Will change this after the this PR docker compose is merged to master.

2024-06-22 12:33 UTC, EddieTheCubeHead commented on infra/main.tf
> +  name = "stagnum.com"
stagnum.net is the correct one

2024-06-22 12:34 UTC, EddieTheCubeHead approved these changes
LGTM

2024-06-22 12:35 UTC, EddieTheCubeHead requested changes
Forgot before clicking approve: need to change to domain still

stagnum.net

2024-06-23 08:23 UTC, ekosfin commented on infra/main.tf
> +  name = "stagnum.com"
updated

2024-06-23 08:38 UTC, EddieTheCubeHead approved these changes

2024-06-23 08:38 UTC, merged