1 setup and document frontend development environment
EddieTheCubeHead/Stagnum pull request #39
Opened 2024-01-25 12:30 UTC by tuomasmustakallio

Initialized next.js application with docker. Added setup guide to README.md

2024-01-25 12:53 UTC, EddieTheCubeHead requested changes

2024-01-25 12:53 UTC, EddieTheCubeHead commented on client/package-lock.json
Please add package-lock to .gitignore and remove the file.

Sometimes getting git to remove a file added to gitignore is a bit finicky so I recommend doing as follows:
 - Delete package-lock
 - Commit and push
 - Add package-lock to gitignore
 - Run npm install again locally to restore your local package-lock copy

2024-01-25 12:53 UTC, EddieTheCubeHead commented on client/public/next.svg
Do we need these two svg files? If not can we remove them?

2024-01-25 12:53 UTC, EddieTheCubeHead commented on client/public/vercel.svg
Do we need these two svg files? If not can we remove them?

2024-01-25 14:16 UTC, ddevarsh7 approved these changes

2024-01-25 14:42 UTC, EddieTheCubeHead commented on client/app/layout.tsx
> +  description: "Generated by create next app",
Sorry for leaving extra comments after the first review:

Can we already set title to "Stagnum" and description to "A pool-based playback handler for Spotify"?

2024-01-28 17:38 UTC, EddieTheCubeHead approved these changes

2024-01-28 18:27 UTC, OttoAhlfors approved these changes

2024-01-28 18:31 UTC, merged