Removed empty package.json and package-lock.json from root
EddieTheCubeHead/Stagnum pull request #53
Opened 2024-02-01 14:22 UTC by KeManen

2024-02-01 14:45 UTC, EddieTheCubeHead requested changes

2024-02-01 14:45 UTC, EddieTheCubeHead commented on package.json
I am not big into UI but to my understanding package.json is required to be in source control (like requirements.txt) while package-lock is not?

2024-02-01 14:45 UTC, EddieTheCubeHead commented on package.json
@tuomasmustakallio @OttoAhlfors can you confirm or deny?

2024-02-01 15:17 UTC, EddieTheCubeHead commented on package.json
But it might be only for packages? In which case it is indeed redundant for us

2024-02-01 15:20 UTC, KeManen commented on package.json
Note the package.json and package-lock.json are from the root folder not the client/ folder.

2024-02-01 15:21 UTC, EddieTheCubeHead commented on package.json
Ah

2024-02-01 15:21 UTC, EddieTheCubeHead approved these changes

2024-02-01 18:03 UTC, tuomasmustakallio approved these changes

2024-02-02 21:04 UTC, BadhonRahman01 approved these changes
!

2024-02-03 15:24 UTC, merged